# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGE_TOKEN}}
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 15
    rebase-strategy: 'disabled'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 15
    rebase-strategy: 'disabled'
    registries:
      - npm-github
    schedule:
      interval: 'weekly'
