imagePullSecrets:
  - name: dockerconfigjson-ghcr

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"

settings:
  hostname: dev.nordeck.systems

env:
  - name: REACT_APP_IGNORE_USER_IDS
    value: "@bot-dev:synapse.dev.nordeck.systems,@meetings-bot:synapse.dev.nordeck.systems"
